version: "3.8"

services:
  gremlin-server:
    container_name: gremlin-server
    image: tinkerpop/gremlin-server
    ports:
      - "8182:8182"

  gremlin-visualizer:
    container_name: gremlin-visualizer
    image: prabushitha/gremlin-visualizer
    ports:
      - "3000:3000"
      - "3001:3001"
